---
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

Configutation:
  name: Default
  Properties:
    Property:
      name: log-path
      value: "logs"
  Appenders:
    Console:
      name: Console_Appender
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
  Loggers:
      Logger:
        level: error
        AppenderRef:
          - ref: Console_Appender

lucky-word: "Irish"
wordConfig:
  luckyWord: abcde991
  preamble: xyza991
